// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UVV_fintech.Db;

#nullable disable

namespace UVV_fintech.Migrations
{
    [DbContext(typeof(BancoDbContext))]
    partial class BancoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UVV_fintech.Model.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("UVV_fintech.Model.Conta", b =>
                {
                    b.Property<int>("ContaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContaId"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("ContaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Contas");

                    b.HasDiscriminator<string>("TipoConta").HasValue("Conta");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UVV_fintech.Model.Transacao", b =>
                {
                    b.Property<int>("TransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransacaoId"));

                    b.Property<int>("ContaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoTransacao")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransacaoId");

                    b.HasIndex("ContaId");

                    b.ToTable("Transacoes");

                    b.HasDiscriminator<string>("TipoTransacao").HasValue("Transacao");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UVV_fintech.Model.ContaCorrente", b =>
                {
                    b.HasBaseType("UVV_fintech.Model.Conta");

                    b.Property<decimal>("TaxaManutencao")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("ContaCorrente");
                });

            modelBuilder.Entity("UVV_fintech.Model.ContaPoupanca", b =>
                {
                    b.HasBaseType("UVV_fintech.Model.Conta");

                    b.Property<decimal>("TaxaRendimento")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("ContaPoupanca");
                });

            modelBuilder.Entity("UVV_fintech.Model.Depositar", b =>
                {
                    b.HasBaseType("UVV_fintech.Model.Transacao");

                    b.HasDiscriminator().HasValue("Deposito");
                });

            modelBuilder.Entity("UVV_fintech.Model.Sacar", b =>
                {
                    b.HasBaseType("UVV_fintech.Model.Transacao");

                    b.HasDiscriminator().HasValue("Saque");
                });

            modelBuilder.Entity("UVV_fintech.Model.Transferir", b =>
                {
                    b.HasBaseType("UVV_fintech.Model.Transacao");

                    b.Property<int>("ContaDestinoId")
                        .HasColumnType("int");

                    b.HasIndex("ContaDestinoId");

                    b.HasDiscriminator().HasValue("Transferencia");
                });

            modelBuilder.Entity("UVV_fintech.Model.Conta", b =>
                {
                    b.HasOne("UVV_fintech.Model.Cliente", "Cliente")
                        .WithMany("Contas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("UVV_fintech.Model.Transacao", b =>
                {
                    b.HasOne("UVV_fintech.Model.Conta", "Conta")
                        .WithMany("Transacoes")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("UVV_fintech.Model.Transferir", b =>
                {
                    b.HasOne("UVV_fintech.Model.Conta", "ContaDestino")
                        .WithMany()
                        .HasForeignKey("ContaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaDestino");
                });

            modelBuilder.Entity("UVV_fintech.Model.Cliente", b =>
                {
                    b.Navigation("Contas");
                });

            modelBuilder.Entity("UVV_fintech.Model.Conta", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
